implemented models
sag333ar/blurt-mobile-app pull request #3
Opened 2023-10-17 14:01 UTC by RAMb002

2023-10-17 15:41 UTC, sag333ar requested changes

2023-10-17 15:41 UTC, sag333ar commented on lib/models/chain_prop_model.dart
> +    String toRawJson() => json.encode(toJson());
we would never require to convert it back to JSON.

2023-10-17 15:41 UTC, sag333ar commented on lib/models/chain_prop_model.dart
> +    Map<String, dynamic> toJson() => {
we would never require to convert it back to JSON

2023-10-17 15:41 UTC, sag333ar commented on lib/models/feed/active_vote_model.dart
> +    Map<String, dynamic> toJson() => {
we would never require to convert it back to JSON

2023-10-17 15:41 UTC, sag333ar commented on lib/models/feed/active_vote_model.dart
> +    ActiveVoteModel copyWith({
What is the purpose of copyWith?

2023-10-17 15:41 UTC, sag333ar commented on lib/models/feed/post_feed_model.dart
> +    final List<dynamic> replies;
`List<dynamic>` - Need a proper type here.

2023-10-17 15:41 UTC, sag333ar commented on lib/models/feed/post_feed_model.dart
> +    final String promoted;
Apart from postId, let's keep everything else optional

2023-10-17 15:41 UTC, sag333ar commented on lib/resources/enum.dart
> +enum FeedType{trending,hot}
`trending`, `hot` & `created`. In future, we may have more types of feed. Once I get to know, I'll share.

2023-10-17 15:41 UTC, sag333ar commented on lib/services/api_service.dart
> +    Map<String, dynamic> data = json.decode(json.decode(responseJson)['data']);
Always look for followings
- Compare identifier. If Id received in response is not matching to the request send, throw error.
- Always check Type from the response. If type isn't matching, throw error.
- Always check error (`json.decode(responseJson)['error']`), if received error, throw error
- Only after passing above validation, assume that we have valid response from platform.

2023-10-17 15:41 UTC, sag333ar commented on lib/services/api_service.dart
> +    String responseJson = await getChainPropsFromNative();
Please change wording from `Native` to `Platform`
e.g. `getChainPropsFromPlatform()`
We are supporting 3 platforms - iOS, Android, Web. Native word is more used for mobile-apps

2023-10-17 15:41 UTC, sag333ar commented on lib/services/mobile_service.dart
> +  const platform = MethodChannel(channel);
We can move the platform to upper level. (not within function)

2023-10-30 09:10 UTC, RAMb002 commented on lib/models/feed/active_vote_model.dart
> +    ActiveVoteModel copyWith({
to prevent mutation sir. Like for example we have an userModel data from the api, now lets say we need to make some changes to the usermodel but also keep the original data, we use copywith, it creates a new instance with the updated data we need.

2023-10-30 09:19 UTC, RAMb002 commented on lib/models/feed/post_feed_model.dart
> +    final List<dynamic> replies;
we are getting empty list for all the postmodel

2023-10-30 10:52 UTC, merged